In [1]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.shape

(891, 15)

percentages of people survived for each class and gender

In [2]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [107]:
titanic['gender'] = titanic['sex']
titanic.loc[titanic['sex'] == 'male', ['gender']] = 'm'
titanic.loc[titanic['sex'] == 'female', ['gender']] = 'f'

In [6]:
titanic[["sex", "gender"]]

        sex gender
0      male      1
1    female      0
2    female      0
3    female      0
4      male      1
..      ...    ...
886    male      1
887  female      0
888  female      0
889    male      1
890    male      1

[891 rows x 2 columns]

In [17]:
titanic.groupby("pclass")["survived"].sum()

pclass
1    136
2     87
3    119
Name: survived, dtype: int64

In [47]:
titanic.groupby("pclass")['gender'].sum()

pclass
1    122
2    108
3    347
Name: gender, dtype: object

In [56]:
titanic.groupby(["pclass"])[['survived']].sum()

        survived
pclass
1            136
2             87
3            119

In [54]:
titanic.groupby(["pclass"])[['survived']].transform('sum')

     survived
0         119
1         136
2         119
3         136
4         119
..        ...
886        87
887       136
888       119
889       136
890       119

[891 rows x 1 columns]

In [57]:
titanic[['pclass', 'sex', 'survived']]

     pclass     sex  survived
0         3    male         0
1         1  female         1
2         3  female         1
3         1  female         1
4         3    male         0
..      ...     ...       ...
886       2    male         0
887       1  female         1
888       3  female         0
889       1    male         1
890       3    male         0

[891 rows x 3 columns]

In [70]:
temp = titanic.groupby(['pclass','sex'])['survived'].transform('sum') / titanic.groupby('pclass')['survived'].transform('sum')

In [88]:
titanic.groupby(['pclass','sex'])['survived'].sum().unstack()['male']/titanic.groupby('pclass')['survived'].sum()

pclass
1    0.330882
2    0.195402
3    0.394958
dtype: float64

In [72]:
titanic.groupby('pclass')['survived'].sum()

pclass
1    136
2     87
3    119
Name: survived, dtype: int64

In [71]:
temp.head()

0    0.394958
1    0.669118
2    0.605042
3    0.669118
4    0.394958
Name: survived, dtype: float64

In [87]:
titanic.groupby(['pclass','sex'])['survived'].sum().unstack().div(titanic.groupby('pclass')['survived'].sum(), axis=0)

sex       female      male
pclass
1       0.669118  0.330882
2       0.804598  0.195402
3       0.605042  0.394958

In [112]:
titanic.groupby(['pclass','survived','sex'])['gender'].count().unstack()

sex              female  male
pclass survived
1      0              3    77
       1             91    45
2      0              6    91
       1             70    17
3      0             72   300
       1             72    47

In [111]:
titanic.groupby(['pclass','survived'])['gender'].count()

pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: gender, dtype: int64

In [117]:
titanic.groupby(['pclass','survived','sex'])['gender'].count().unstack().div(titanic.groupby(['pclass','survived'])['gender'].count(), axis=0).unstack()

sex         female                male
survived         0         1         0         1
pclass
1         0.037500  0.669118  0.962500  0.330882
2         0.061856  0.804598  0.938144  0.195402
3         0.193548  0.605042  0.806452  0.394958