In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'stock': ['INFY', "TCL", 'BEL'],
    'price': [500, 150, 750],
    'quantity': [10, 20, 15]
})

In [4]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [5]:
df.iloc[2]

stock       BEL
price       750
quantity     15
Name: 2, dtype: object

In [6]:
df.iloc[0:3]

  stock  price  quantity
0  INFY    500        10
1   TCL    150        20
2   BEL    750        15

In [7]:
df.iloc[1,2]

np.int64(20)

In [8]:
int(df.iloc[1, 2])

20

In [9]:
df.loc[0]

stock       INFY
price        500
quantity      10
Name: 0, dtype: object

In [24]:
df.loc[0:1]

  stock  price  quantity
0  INFY    500        10
1   TCL    150        20

In [10]:
df2 = df.set_index('stock')

In [13]:
df2

       price  quantity
stock
INFY     500        10
TCL      150        20
BEL      750        15

In [12]:
df2.loc['INFY']

price       500
quantity     10
Name: INFY, dtype: int64

In [18]:
df.iloc[0, 1]

np.int64(500)

In [23]:
df.loc[0, 'price']

np.int64(500)