In [13]:
import pandas as pd

In [14]:
df = pd.DataFrame({
    'Stock': ['TCS', 'INFY', 'BEL', 'NVDA'],
    'Price': [300, 1500, 200, 500],
    'quantity': [5, 10, 15, 56]
})

In [15]:
df[['Price']] >200

   Price
0   True
1   True
2  False
3   True

In [16]:
df[df[['Price']]> 200]

  Stock   Price  quantity
0   NaN   300.0       NaN
1   NaN  1500.0       NaN
2   NaN     NaN       NaN
3   NaN   500.0       NaN

In [18]:
df[(df['Price']>200) & (df['quantity']> 10)]

  Stock  Price  quantity
3  NVDA    500        56

In [20]:
df[(df['Price']> 300) | (df['quantity']> 40)]

  Stock  Price  quantity
1  INFY   1500        10
3  NVDA    500        56

In [22]:
df.loc[(df['Price'] > 200), ['Stock']]

  Stock
0   TCS
1  INFY
3  NVDA

In [25]:
df[df['Stock'].isin(['RELIANCE', 'TCS'])]
df['Stock'].isin(['RELIANCE', 'TCS'])

0     True
1    False
2    False
3    False
Name: Stock, dtype: bool

In [39]:
df[df["Price"] > 300][["Price", "Price"]]

   Price  Price
1   1500   1500
3    500    500