
# Groupby

In [1]:
import pandas as pd

df = pd.DataFrame({
    "sector": ["IT", "IT", "Energy", "Energy", "IT"],
    "stock": ["INFY", "TCS", "RELIANCE", "ONGC", "WIPRO"],
    "price": [1000, 2000, 1500, 1200, 800],
    "qty": [10, 20, 15, 12, 8]
})

In [2]:
df

   sector     stock  price  qty
0      IT      INFY   1000   10
1      IT       TCS   2000   20
2  Energy  RELIANCE   1500   15
3  Energy      ONGC   1200   12
4      IT     WIPRO    800    8

In [6]:
temp = df.groupby("sector")
temp["price"].mean()

sector
Energy    1350.000000
IT        1266.666667
Name: price, dtype: float64

In [22]:
temp.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [19]:
temp

In [13]:
temp['price'].min()
temp['price'].max()

sector
Energy    1500
IT        2000
Name: price, dtype: int64

In [11]:
temp.agg({
    'price': 'mean',
    'qty': 'sum'
})

              price  qty
sector
Energy  1350.000000   27
IT      1266.666667   38

In [14]:
temp['price'].agg(['mean', 'min', 'max'])

               mean   min   max
sector
Energy  1350.000000  1200  1500
IT      1266.666667   800  2000

In [15]:
temp['qty'].agg(['min', 'max', 'sum', 'mean'])

        min  max  sum       mean
sector
Energy   12   15   27  13.500000
IT        8   20   38  12.666667

In [18]:
temp['price'].mean()

sector
Energy    1350.000000
IT        1266.666667
Name: price, dtype: float64

In [17]:
temp['price'].mean().reset_index()

   sector        price
0  Energy  1350.000000
1      IT  1266.666667

In [23]:
df

   sector     stock  price  qty
0      IT      INFY   1000   10
1      IT       TCS   2000   20
2  Energy  RELIANCE   1500   15
3  Energy      ONGC   1200   12
4      IT     WIPRO    800    8

In [26]:
df.groupby('sector')[['price']].transform('mean').reset_index()

   index        price
0      0  1266.666667
1      1  1266.666667
2      2  1350.000000
3      3  1350.000000
4      4  1266.666667

In [27]:
df['price_to_sector'] = df['price'] / df.groupby('sector')['price'].transform('mean')

In [28]:
df

   sector     stock  price  qty  price_to_sector
0      IT      INFY   1000   10         0.789474
1      IT       TCS   2000   20         1.578947
2  Energy  RELIANCE   1500   15         1.111111
3  Energy      ONGC   1200   12         0.888889
4      IT     WIPRO    800    8         0.631579