In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Stock': ['TCL', 'TCV', "POWERGRID"],
    'Price': [740, 455, 430],
    'Quantity': [117, 23, 45]
})

In [3]:
df['Price']

0    740
1    455
2    430
Name: Price, dtype: int64

In [4]:
df.Price

0    740
1    455
2    430
Name: Price, dtype: int64

In [5]:
df['Stock']

0          TCL
1          TCV
2    POWERGRID
Name: Stock, dtype: object

In [6]:
type(df["Stock"]) # though : data frame but got data series

pandas.core.series.Series

In [7]:
type(df[['Stock']]) # data frame

pandas.core.frame.DataFrame

In [8]:
df[['Price', 'Stock', 'Price']]

   Price      Stock  Price
0    740        TCL    740
1    455        TCV    455
2    430  POWERGRID    430

In [9]:
'Pri' in df.columns

False

In [28]:
df = pd.DataFrame({
    'Stock': ['TCL', 'INFY', "COALINDIA"],
    'Price': [740, 455, 430],
    'Quantity': [117, 23, 45]
}, index=['TCL', 'INFY', "COALINDIA"])

In [29]:
df

               Stock  Price  Quantity
TCL              TCL    740       117
INFY            INFY    455        23
COALINDIA  COALINDIA    430        45

In [30]:
df[:"INFY"]

     Stock  Price  Quantity
TCL    TCL    740       117
INFY  INFY    455        23

In [25]:
df.loc[:2]

  Stock  Price  Quantity
0   TCL    740       117
1   TCL    455        23
2   TCL    430        45

In [ ]:
df.loc[df['Stock'] == 'TCL', :]

  Stock  Price  Quantity
0   TCL    740       117
1   TCL    455        23