In [5]:
import pandas as pd

df = pd.DataFrame({
    'stocks': ['INFY', 'TCS', 'COALINDIA'],
    'price': [100, 150, 300],
    'qty': [10, 10, 30]
})

This is called vectorization (powered by NumPy underneath).

In [6]:
df['value'] = df['price'] * df['qty']

In [7]:
df

      stocks  price  qty  value
0       INFY    100   10   1000
1        TCS    150   10   1500
2  COALINDIA    300   30   9000

In [18]:
df['test'] = 'normal'

In [19]:
df

      stocks  price  qty  value category    test
0       INFY    100   10   1000   normal  normal
1        TCS    150   10   1500   normal  normal
2  COALINDIA    300   30   9000   normal  normal

In [24]:
df.loc[df['price'] > 100, ['category']] = 'expensive'

In [25]:
df

      stocks  price  qty  value   category    test
0       INFY    100   10   1000     normal  normal
1        TCS    150   10   1500  expensive  normal
2  COALINDIA    300   30   9000  expensive  normal